### PR TITLE
Help Menu

### PR DESCRIPTION
**Pull request by garrettsummerfi3ld**
### Information

This is the complete help menu for the GalaxeSMP. All documented and accessible through the user.

### Details

**Proposed feature:**

Big help menu for all items in the GalaxeSMP. Has smaller help menus for other aspects of the server.

**Environments tested:**

OS: Linux

Java version: 17

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] Most recent GeyserMC version (2.XX.Y)

**Demonstration:**

image
image
image

### CODE REVIEW

**Comment by garrettsummerfi3ld** [comment]
[Develop a /help GUI for a visual menu to improve accessibility](https://trello.com/c/pgL7uTHK/66-develop-a-help-gui-for-a-visual-menu-to-improve-accessibility)

**Comment by josefbaltz** [comment]
we probably want to have a section explaining classes. last thing we want is players selecting a class like skeleton then leaving spawn and being set on fire

**Comment by garrettsummerfi3ld** [comment]
> we probably want to have a section explaining classes. last thing we want is players selecting a class like skeleton then leaving spawn and being set on fire

Are we sure we want to put all the help documentation into this plugin from Genesis? I am thinking that this is out of scope for this specific plugin, I _can_ integrate a section for it, but I'd also think Genesis should have its own menus and documentation.

**Comment by josefbaltz** [comment]
> > we probably want to have a section explaining classes. last thing we want is players selecting a class like skeleton then leaving spawn and being set on fire
> 
> Are we sure we want to put all the help documentation into this plugin from Genesis? I am thinking that this is out of scope for this specific plugin, I _can_ integrate a section for it, but I'd also think Genesis should have its own menus and documentation.

we shouldn't have absolutely everything but we should still have a mention that explains that the plugin exists and how to access the plugin's GUI selection screen

**Comment by garrettsummerfi3ld** [comment]
> we shouldn't have absolutely everything but we should still have a mention that explains that the plugin exists and how to access the plugin's GUI selection screen
> 
> it's a help plugin specific for the server, should have help content over everything we have that's integral to the server.

@josefbaltz this is now resolved in commit e9db012.

**Review by tonyswink — APPROVED** [review]

**Pull request merged**
